# Generated by Django 5.2.7 on 2025-11-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_field_profile_address_profile_age_profile_coach_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='team_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
