# Generated by Django 5.2.7 on 2025-11-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_google_access_token_profile_google_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
