# Generated by Django 5.2.7 on 2025-11-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_google_access_token_profile_google_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coach_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='team_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='team_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
