# Generated by Django 5.2.7 on 2025-11-02 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile_coach_name_profile_profile_completed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='max_participants',
        ),
        migrations.AddField(
            model_name='tournament',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/banners/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_players_per_team',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_teams',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='tournament',
            name='min_players_per_team',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sponsors',
            field=models.TextField(blank=True, help_text='Comma-separated sponsor names', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_format',
            field=models.CharField(choices=[('round_robin', 'Round Robin'), ('single_elimination', 'Single Elimination'), ('double_elimination', 'Double Elimination'), ('pool_play', 'Pool Play')], default='round_robin', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('coach', 'Coach'), ('volunteer', 'Volunteer'), ('admin', 'Admin'), ('tournament_director', 'Tournament Director'), ('team_manager', 'Team Manager'), ('referee', 'Referee'), ('scorer', 'Scorer')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('registration_open', 'Registration Open'), ('registration_closed', 'Registration Closed'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_details', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='api.tournament')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('round_number', models.IntegerField(default=1)),
                ('match_number', models.IntegerField()),
                ('team_a_score', models.IntegerField(default=0)),
                ('team_b_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='api.field')),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refereed_matches', to=settings.AUTH_USER_MODEL)),
                ('scorer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scored_matches', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.tournament')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['match_date', 'start_time', 'field'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner (0-1 years)'), ('intermediate', 'Intermediate (1-3 years)'), ('advanced', 'Advanced (3-5 years)'), ('expert', 'Expert (5+ years)')], default='beginner', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.tournament')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['jersey_number', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=False)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='api.tournament')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='api.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='api.player')),
            ],
            options={
                'ordering': ['date', 'player'],
                'unique_together': {('player', 'match', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('home_city', models.CharField(blank=True, max_length=255, null=True)),
                ('team_logo', models.ImageField(blank=True, null=True, upload_to='teams/logos/')),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('points_for', models.IntegerField(default=0)),
                ('points_against', models.IntegerField(default=0)),
                ('average_spirit_score', models.FloatField(default=0.0)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captained_teams', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='api.tournament')),
            ],
            options={
                'ordering': ['-wins', '-average_spirit_score'],
                'unique_together': {('tournament', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SpiritScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_knowledge', models.IntegerField(default=2, help_text='Rules Knowledge & Use (0-4)')),
                ('fouls_and_contact', models.IntegerField(default=2, help_text='Fouls & Body Contact (0-4)')),
                ('fair_mindedness', models.IntegerField(default=2, help_text='Fair-Mindedness (0-4)')),
                ('positive_attitude', models.IntegerField(default=2, help_text='Positive Attitude & Self-Control (0-4)')),
                ('communication', models.IntegerField(default=2, help_text='Communication (0-4)')),
                ('comments', models.TextField(blank=True, help_text='Optional feedback', null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spirit_scores', to='api.match')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_spirit_scores', to=settings.AUTH_USER_MODEL)),
                ('receiving_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_spirit_scores', to='api.team')),
                ('scoring_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_spirit_scores', to='api.team')),
            ],
            options={
                'unique_together': {('match', 'scoring_team', 'receiving_team')},
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_a', to='api.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_b', to='api.team'),
        ),
        migrations.CreateModel(
            name='TournamentAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='api.tournament')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('purpose', models.CharField(blank=True, max_length=100, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='api.tournament')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.DeleteModel(
            name='TournamentRegistration',
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('tournament', 'email')},
        ),
    ]
