# Generated by Django 5.2.7 on 2025-11-03 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_team_role'),
        ('api', '0004_profile_coach_name_profile_profile_completed_and_more'),
        ('api', '0004_tournament_notification_sent'),
    ]

    operations = [
    ]
