# Generated by Django 5.2.7 on 2025-11-03 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20251103_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='participants',
        ),
        migrations.AlterUniqueTogether(
            name='tournamentregistration',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tournamentregistration',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournamentregistration',
            name='user',
        ),
        migrations.DeleteModel(
            name='FitnessLog',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='TournamentRegistration',
        ),
    ]
