"""
Django settings for fitness_backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-+-j%fovtpmu25nr9g$31*92@*(-ked1qbsoi7de)cf208a@y7b')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else ['*']


# CORS Configuration for Next.js frontend
CORS_ALLOW_ALL_ORIGINS = True  # For development only
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://localhost:3002",
    "http://127.0.0.1:3000",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',  # Django REST Framework
    'rest_framework.authtoken',  # Token authentication
    'corsheaders',  # Django CORS Headers
    'pwa',# Django PWA
    'api.apps.ApiConfig',
    # Your project apps go here
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware (must be before CommonMiddleware)
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fitness_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug', # Added for pwa/offline template
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fitness_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Supabase PostgreSQL configuration (or local SQLite for development)
USE_SUPABASE = os.environ.get('USE_SUPABASE', 'False') == 'True'

if USE_SUPABASE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'postgres'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('DB_PASSWORD', '12345678'),
            'HOST': os.environ.get('DB_HOST', 'db.xnhnrsoqbmcursawxjoq.supabase.co'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    # SQLite for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    
# Psycopg2 is required for PostgreSQL, which uses 'django.db.backends.postgresql'
# No direct settings.py config is needed for psycopg2-binary, as it's the Python package
# used by Django's PostgreSQL engine. The engine name handles the connection:
# DATABASES['default']['ENGINE'] = 'django.db.backends.postgresql' 


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' # Needed for deployment and PWA
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (User uploads like profile pictures)
# https://docs.djangoproject.com/en/5.2/ref/settings/#media-root
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- Django REST Framework Settings ---
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', # Require authentication by default
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # Token auth for API
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication'
    ],
    # You can add more settings here like pagination, filters, etc.
}


# --- Django PWA Settings ---
PWA_APP_NAME = os.environ.get('PWA_APP_NAME', 'Fitness Backend')
PWA_APP_DESCRIPTION = os.environ.get('PWA_APP_DESCRIPTION', 'My Fitness Application')
PWA_APP_THEME_COLOR = os.environ.get('PWA_APP_THEME_COLOR', '#000000')
PWA_APP_BACKGROUND_COLOR = os.environ.get('PWA_APP_BACKGROUND_COLOR', '#ffffff')
PWA_APP_DISPLAY = os.environ.get('PWA_APP_DISPLAY', 'standalone')
PWA_APP_ORIENTATION = os.environ.get('PWA_APP_ORIENTATION', 'portrait')
PWA_APP_START_URL = os.environ.get('PWA_APP_START_URL', '/')
PWA_APP_SCOPE = os.environ.get('PWA_APP_SCOPE', '/')
PWA_APP_STATUS_BAR_COLOR = os.environ.get('PWA_APP_STATUS_BAR_COLOR', 'default')

PWA_APP_ICONS = [
    {
        'src': '/static/images/my_app_icon.png', # Placeholder - replace with your icon path
        'sizes': '192x192'
    }
]

# Set the path to your custom service worker
PWA_SERVICE_WORKER_PATH = BASE_DIR / 'static/js/serviceworker.js'